v0.1 base64converter
lokihi/base64converter pull request #2
Opened 2024-09-03 08:00 UTC by lokihi

2024-09-03 10:17 UTC, aasirotkin approved these changes
Написал замечания, если что непонятно, пиши

2024-09-03 10:17 UTC, aasirotkin commented on CMakeLists.txt
> +  base64_basic_test
Зачем два executable? одного будет достаточно

2024-09-03 10:17 UTC, aasirotkin commented on README.md
> +- Encoding
В readme хорошо ещё писать зависимости и стандарт языка. Ещё примеры использования можно добавить.

2024-09-03 10:17 UTC, aasirotkin commented on include/base64.hpp
> +std::array<char, 64> constexpr encodeTable
constexpr должно быть в самом начале и везде ниже тоже

2024-09-03 10:17 UTC, aasirotkin commented on include/base64.hpp
> +    const uint8_t *inputIterator = reinterpret_cast<const uint8_t *>(&inputString[0]);
Тут const перед, а сверху constexpr после? Должно быть везде однотипно, как здесь

2024-09-03 10:17 UTC, aasirotkin commented on include/base64.hpp
> +    // Size of input string //
Не рекомендуется писать очевидные комментарии. Лучше тут и ниже везде убрать, где очевидно, что делается

2024-09-03 10:17 UTC, aasirotkin commented on include/base64.hpp
> +
Лишний перенос строки

2024-09-03 10:17 UTC, aasirotkin commented on include/base64.hpp
> +    for (size_t i = inputDataSize / 3; i; --i)
```
for (size_t i = inputDataSize / 3; i; --i)
```
какое-то хитрое условие выхода. Перепиши пожалуйста так, чтобы было очевидно

2024-09-03 10:17 UTC, aasirotkin commented on include/base64.hpp
> +        encodedString.push_back(encodeTable[(concatenatedBits >> 18) & 0b0011'1111]);
Весь это цикл (for) рекомендую вынести в отдельный метод. Подумай сам как и что он должен делать. Расскажи мне прежде чем писать.

2024-09-03 10:17 UTC, aasirotkin commented on include/base64.hpp
> +
Лишний перенос

2024-09-03 10:17 UTC, aasirotkin commented on include/base64.hpp
> +    const size_t numPadding = std::count(inputString.rbegin(), inputString.rbegin() + 4, '=');
Насколько эффективно искать эти символы в 3 циклах?
Сейчас оставь так, а потом может быть сделаем за один цикл

2024-09-03 10:17 UTC, aasirotkin commented on include/base64.hpp
> +        throw std::runtime_error{
Сейчас оставь так, а потом переделаем это место, чтобы не было исключений

2024-09-03 10:17 UTC, aasirotkin commented on include/base64.hpp
> +    size_t sizeDecoded = (inputDataSize / 4 * 3) - numPadding;
Почему не const?

2024-09-03 10:17 UTC, aasirotkin commented on include/base64.hpp
> +    int counterBlock = 0;
Почему int? везде size_t

2024-09-03 10:17 UTC, aasirotkin commented on include/base64.hpp
> +    for (size_t i = 0; i < inputDataSize - (numPadding!=0)*4; i++)
Посчитай размер заранее inputDataSize - (numPadding!=0)*4;

2024-09-03 10:17 UTC, aasirotkin commented on include/base64.hpp
> +        decodedString.push_back((concatenatedBits >> 8) & 0b1111'1111);
Подумай как декомпозировать эту функцию тоже. Она очень длинная, сложно читать

2024-09-03 10:17 UTC, aasirotkin commented on include/base64.hpp
> +}
Нужен перенос строки

2024-09-03 10:17 UTC, aasirotkin commented on test/base64_file_test.cpp
> +    std::string const expected{buffer.str()};
ты уверен, что строка не пустая?

2024-09-03 10:17 UTC, aasirotkin commented on test/base64_test.cpp
> +// TEST FOR EMPTY INPUT //
Лишние комментарии, они дублируют названия тестов

2024-09-03 10:51 UTC, lokihi commented on include/base64.hpp
> +        encodedString.push_back(encodeTable[(concatenatedBits >> 18) & 0b0011'1111]);
По поводу отдельного метода, можно тогда в функцию вынести для кодирования блока из 3 символов
Или если весь цикл for выносить, то можно тогда string_view передавать,  а возвращать строку без добавления padding char в конце

2024-09-03 10:56 UTC, aasirotkin commented on include/base64.hpp
> +        encodedString.push_back(encodeTable[(concatenatedBits >> 18) & 0b0011'1111]);
думаю, что весь for хорошо будет вынести

2024-09-03 10:56 UTC, aasirotkin commented on include/base64.hpp
> +        encodedString.push_back(encodeTable[(concatenatedBits >> 18) & 0b0011'1111]);
и думаю что ты правильно понял идею. Свитч скорее всего тоже можно вынести))

2024-09-03 10:56 UTC, aasirotkin commented on include/base64.hpp
> +        encodedString.push_back(encodeTable[(concatenatedBits >> 18) & 0b0011'1111]);
но в другой метод

2024-09-03 10:58 UTC, aasirotkin commented on test/base64_file_test.cpp
> +}
Обрати внимание, у некоторых файлов есть такие кирпичи в конце. Это значит, что нет переноса строки. Рекомендую всегда делать перенос на новую строку.

2024-09-03 11:07 UTC, lokihi commented on include/base64.hpp
> +        encodedString.push_back(encodeTable[(concatenatedBits >> 18) & 0b0011'1111]);
А можно передавать в метод указатель на уже созданную строку для вывода, и сделать функцию void?

2024-09-03 11:18 UTC, aasirotkin commented on include/base64.hpp
> +        encodedString.push_back(encodeTable[(concatenatedBits >> 18) & 0b0011'1111]);
давай так попробуем. Сделай это в namespace detail {} внутри твоего namespace

2024-09-03 11:53 UTC, lokihi commented on include/base64.hpp
> +    const size_t numPadding = std::count(inputString.rbegin(), inputString.rbegin() + 4, '=');
Циклы для поиска Return и Newline лишними были. Пытался одно исключение проверить и забыл удалить.  В цикл для декодирования уже встроено игнорирование этих символов

2024-09-06 05:09 UTC, aasirotkin approved these changes
Ответил. Давай поправим эти замечания и думаю выйдем на финишную прямую.
Если сделал какой-то пункт, то напиши в сообщении "Сделал", я тогда будут понимать, что этот вопрос можно закрыть.

2024-09-06 05:09 UTC, aasirotkin commented on include/base64.hpp
> +    }
Некоторые компиляторы могут думать, что ты забыл default и будут делать предупреждение, а у нас 0-ая политика по отношению к предупреждениям, то есть это будет ошибка. Добавь пожалуйста default

2024-09-06 05:09 UTC, aasirotkin commented on include/base64.hpp
> +        if (currentBlock[counterBlock] != '\n' && currentBlock[counterBlock]!='\r') counterBlock++;
По кодстайлу так нельзя, нужно перенести тело if на новую строку

2024-09-06 05:09 UTC, aasirotkin commented on include/base64.hpp
> +        std::uint32_t const concatenatedBits =
Тут поехало форматирование

2024-09-06 05:09 UTC, aasirotkin commented on include/base64.hpp
> +            (decodeTable[currentBlock[0]] << 18) | (decodeTable[currentBlock[1]] << 12) | (decodeTable[currentBlock[2]] << 6) | decodeTable[currentBlock[3]];
Форматируй так, чтобы было меньше 120 символов

2024-09-06 05:09 UTC, aasirotkin commented on include/base64.hpp
> +}
Нужен перенос строки

2024-09-06 05:09 UTC, aasirotkin commented on include/base64.hpp
> +    encodedString.reserve(sizeEncoded);
Может reserve перенесём в mainPartString? а то там push back делается, и не очевидно, что ранее был reserve

2024-09-06 05:09 UTC, aasirotkin commented on include/base64.hpp
> +
Лишние переносы строк

2024-09-06 05:09 UTC, aasirotkin commented on include/base64.hpp
> +    decodedString.reserve(sizeDecoded);
Возможно тоже самое, посмотри

2024-09-06 05:09 UTC, aasirotkin commented on include/base64.hpp
> +            "Invalid base64 string. Couldn't resolve ammount of paddinngs."};
Давай сделаем так. Добавим ещё одну функцию decode(inputString, bool isError).

Если пользователь вызывает без флага, то выбрасывается исключение, а если с флагом, то флаг выставляется в false и возвращается пустая строка

2024-09-06 05:09 UTC, aasirotkin commented on include/base64.hpp
> +        return std::string{};
Может давай уберём эту проверку? Насколько это частый кейс, что мы конвертим пустую строку? А вид портит

2024-09-06 05:09 UTC, aasirotkin commented on include/base64.hpp
> +            "Invalid base64 string. Couldn't resolve ammount of paddinngs."};
И ещё, забыл, напиши на этот случай тесты, и с флагом и с исключением

2024-09-06 05:09 UTC, aasirotkin commented on test/base64_test.cpp
> +    std::string const expected{};
В тестах везде тоже нужно поправить и перенести const в начало

2024-09-06 05:09 UTC, aasirotkin commented on test/base64_test.cpp
> +#include "../include/base64.hpp"
по кодстайлу сначала подключаем сторонние файлы, потом, через перенос строки, свои

2024-09-06 05:09 UTC, aasirotkin commented on include/base64.hpp
> +// Decoding table for base 64 converter //
Тоже вот, как будто бы это очевидно из названии переменной

2024-09-06 05:09 UTC, aasirotkin commented on include/base64.hpp
> +    for (size_t i = 0; i < inputString.size() / 3; i++)
Погугли чем отличается i++ и ++i, выбери тут подходящий

2024-09-06 05:09 UTC, aasirotkin commented on include/base64.hpp
> +        const uint8_t symbol3 = *inputIterator++;
Тоже самое, чем отличается ++ после, от ++ до

2024-09-06 05:09 UTC, aasirotkin commented on include/base64.hpp
> +    case 0:
Вот тут можно сделать комментарий
case 0: // Что значит этот ноль
case 1: // Что такое один
и так далее

2024-09-06 05:09 UTC, aasirotkin commented on include/base64.hpp
> +    detail::decodingPaddingChar(inputString, numPadding, decodedString);
Сверху, в encode, есть перенос между вызовами функций, а тут нет

2024-09-06 05:09 UTC, aasirotkin commented on include/base64.hpp
> +        return std::string{};
Тебе нужно, чтобы строка была не пустая, а может быть кратная 4?

2024-09-06 05:09 UTC, aasirotkin commented on README.md
> +- Encoding
Добавь пожалуйста и расскажи, что можно декодировать двумя методами, а какими прочитаешь внизу

2024-09-06 12:44 UTC, lokihi commented on include/base64.hpp
> +        const uint8_t symbol3 = *inputIterator++;
Сделал

2024-09-06 12:44 UTC, lokihi commented on include/base64.hpp
> +}
Сделал

2024-09-06 12:45 UTC, lokihi commented on include/base64.hpp
> +            (decodeTable[currentBlock[0]] << 18) | (decodeTable[currentBlock[1]] << 12) | (decodeTable[currentBlock[2]] << 6) | decodeTable[currentBlock[3]];
Сделал

2024-09-06 12:45 UTC, lokihi commented on include/base64.hpp
> +        std::uint32_t const concatenatedBits =
Сделал

2024-09-06 12:45 UTC, lokihi commented on include/base64.hpp
> +        if (currentBlock[counterBlock] != '\n' && currentBlock[counterBlock]!='\r') counterBlock++;
Сделал

2024-09-06 12:45 UTC, lokihi commented on include/base64.hpp
> +    }
Сделал

2024-09-06 12:50 UTC, lokihi commented on include/base64.hpp
> +    encodedString.reserve(sizeEncoded);
Сделал

2024-09-06 12:50 UTC, lokihi commented on include/base64.hpp
> +    decodedString.reserve(sizeDecoded);
Сделал

2024-09-06 12:50 UTC, lokihi commented on include/base64.hpp
> +
Сделал

2024-09-06 12:52 UTC, lokihi commented on include/base64.hpp
> +            "Invalid base64 string. Couldn't resolve ammount of paddinngs."};
То есть это как доп параметр в функцию подаётся?

2024-09-06 12:53 UTC, lokihi commented on test/base64_test.cpp
> +    std::string const expected{};
Сделал

2024-09-06 12:53 UTC, lokihi commented on test/base64_test.cpp
> +#include "../include/base64.hpp"
Сделал

2024-09-06 12:53 UTC, lokihi commented on include/base64.hpp
> +// Decoding table for base 64 converter //
Сделал

2024-09-06 12:54 UTC, lokihi commented on include/base64.hpp
> +    for (size_t i = 0; i < inputString.size() / 3; i++)
Сделал

2024-09-06 13:19 UTC, lokihi commented on include/base64.hpp
> +        return std::string{};
Проверку на кратность с учетом newline добавил. Конвертацию пустой строки я бы оставил, так как иначе segfault можно словить при определении количества padding char в конце строки

2024-09-06 14:04 UTC, aasirotkin requested changes
Дим, не делай resolve, это я должен сделать. Просто как-то маякни, что всё готово, напиши сделал или ок или ещё что, можно плюсик поставить)

2024-09-06 14:04 UTC, aasirotkin commented on include/base64.hpp
> +            "Invalid base64 string. Couldn't resolve ammount of paddinngs."};
У нас будет две функции
decode(std::string_view inputString) - тут выбрасывается исключение
decode(std::string_view inputString, bool& isOk) - тут isOk = false, если что не так пошло

Так в бусте делают, только у них там error_code.

2024-09-06 14:04 UTC, aasirotkin commented on test/base64_file_test.cpp
> +    ASSERT_EQ(expected, actual);
Добавь проверку, что expected не пустая

2024-09-06 14:04 UTC, aasirotkin commented
И там сверху у тебя ещё есть не выполненные пункты

2024-09-06 14:16 UTC, lokihi commented on CMakeLists.txt
> +  base64_basic_test
Сделал

2024-09-06 14:16 UTC, lokihi commented on include/base64.hpp
> +std::array<char, 64> constexpr encodeTable
Сделал

2024-09-06 14:16 UTC, lokihi commented on include/base64.hpp
> +    const uint8_t *inputIterator = reinterpret_cast<const uint8_t *>(&inputString[0]);
Сделал

2024-09-06 14:16 UTC, lokihi commented on include/base64.hpp
> +    // Size of input string //
Сделал

2024-09-06 14:16 UTC, lokihi commented on include/base64.hpp
> +
Сделал

2024-09-06 14:16 UTC, lokihi commented on include/base64.hpp
> +    for (size_t i = inputDataSize / 3; i; --i)
Сделал

2024-09-06 14:16 UTC, lokihi commented on include/base64.hpp
> +        encodedString.push_back(encodeTable[(concatenatedBits >> 18) & 0b0011'1111]);
Сделал

2024-09-06 14:16 UTC, lokihi commented on include/base64.hpp
> +
Сделал

2024-09-06 14:16 UTC, lokihi commented on include/base64.hpp
> +    const size_t numPadding = std::count(inputString.rbegin(), inputString.rbegin() + 4, '=');
Сделал

2024-09-06 14:17 UTC, lokihi commented on include/base64.hpp
> +    size_t sizeDecoded = (inputDataSize / 4 * 3) - numPadding;
Сделал

2024-09-06 14:17 UTC, lokihi commented on include/base64.hpp
> +    int counterBlock = 0;
Сделал

2024-09-06 14:17 UTC, lokihi commented on include/base64.hpp
> +    for (size_t i = 0; i < inputDataSize - (numPadding!=0)*4; i++)
Сделал

2024-09-06 14:17 UTC, lokihi commented on include/base64.hpp
> +        decodedString.push_back((concatenatedBits >> 8) & 0b1111'1111);
Сделал

2024-09-06 14:17 UTC, lokihi commented on include/base64.hpp
> +}
Сделал

2024-09-06 14:17 UTC, lokihi commented on test/base64_test.cpp
> +// TEST FOR EMPTY INPUT //
Сделал

2024-09-06 14:17 UTC, lokihi commented on test/base64_file_test.cpp
> +}
Сделал

2024-09-06 14:19 UTC, lokihi commented on include/base64.hpp
> +        return std::string{};
Сделал

2024-09-06 14:19 UTC, lokihi commented on include/base64.hpp
> +    case 0:
Сделал

2024-09-06 14:24 UTC, lokihi commented on test/base64_file_test.cpp
> +    ASSERT_EQ(expected, actual);
Сделал

2024-09-06 14:34 UTC, lokihi commented on test/base64_file_test.cpp
> +    std::string const expected{buffer.str()};
Сделал

2024-09-06 14:47 UTC, lokihi commented on include/base64.hpp
> +            "Invalid base64 string. Couldn't resolve ammount of paddinngs."};
Сделал

2024-09-06 15:10 UTC, lokihi commented on README.md
> +- Encoding
Сделал

2024-09-09 07:04 UTC, aasirotkin approved these changes

2024-09-09 07:04 UTC, aasirotkin commented on README.md
> +If an exception is caught, the value of the иoolean variable will be changed to false
Опечатка

2024-09-09 07:04 UTC, aasirotkin commented on include/base64.hpp
> +        const uint8_t symbol1 = *inputIterator++;
у итератора ты решил не менять?

2024-09-09 07:04 UTC, aasirotkin commented on include/base64.hpp
> +        counterBlock++;
Почему тут ++ после?

2024-09-09 07:04 UTC, aasirotkin commented on include/base64.hpp
> +        currentBlock[counterBlock] = *inputIterator++;
Почему тут ++ после?

2024-09-09 07:04 UTC, aasirotkin commented on include/base64.hpp
> +inline void decodingMainPartString(std::string_view inputString, int numPadding, std::string &outputString)
Почему numPadding имеет тип int?

2024-09-09 07:04 UTC, aasirotkin commented on include/base64.hpp
> +        counterBlock++;
и форматирование поехало

2024-09-09 07:04 UTC, aasirotkin commented on include/base64.hpp
> +        std::uint32_t const concatenatedBits = (decodeTable[currentBlock[0]] << 18) | (decodeTable[currentBlock[1]] << 12) |
отступ поехал

2024-09-09 07:04 UTC, aasirotkin commented on include/base64.hpp
> +        std::uint32_t const concatenatedBits = (decodeTable[currentBlock[0]] << 18) | (decodeTable[currentBlock[1]] << 12) |
и почему const посередине?

2024-09-09 07:04 UTC, aasirotkin commented on include/base64.hpp
> +inline void decodingPaddingChar(std::string_view inputString, int numPadding, std::string &outputString)
почему numPadding int? он может быть отрицательным?

2024-09-09 07:04 UTC, aasirotkin commented on include/base64.hpp
> +    case 0:
нужен комментарий к 0 1 2

2024-09-09 07:04 UTC, aasirotkin commented on include/base64.hpp
> +
лишний перенос

2024-09-09 07:04 UTC, aasirotkin commented on test/base64_file_test.cpp
> +#include <gtest/gtest.h>
Долгая история, но лучше отделять разные библиотеки при подключении. То есть тут есть gtest и std.
Добавь перенос

2024-09-09 07:04 UTC, aasirotkin commented on test/base64_file_test.cpp
> +#include <gtest/gtest.h>
и так везде, не только здесь

2024-09-09 07:04 UTC, aasirotkin commented on test/base64_test.cpp
> +    const std::string decoded{base64::decode({"123"},flag)};
Пробел после запятой

2024-09-09 07:04 UTC, aasirotkin commented on test/base64_test.cpp
> +    ASSERT_EQ(expected, flag);
Тут лучше писать ASSERT_TRUE или ASSERT_FALSE, тогда не нужна будет переменная expected.

2024-09-09 07:04 UTC, aasirotkin commented on include/base64.hpp
> +        isOk = false;
Может быть не нужно идти дальше, если isOk уже false?

2024-09-09 07:04 UTC, aasirotkin commented on include/base64.hpp
> +    if ((inputDataSize-ammountNewline)%4!=0)
!= нужно обособить пробелами

2024-09-09 07:04 UTC, aasirotkin commented on include/base64.hpp
> +inline std::string decode(std::string_view inputString)
Самое главное.

У тебя получилось два одинаковых метода. Преимущество этого метода в том, что у тебя сообщение есть, но в версии с bool такого сообщения нет. Предлагаю тут тоже отказаться от двух разных сообщений.

Тогда тебе нужно сделать следующее.

```
inline std::string decode(std::string_view inputString)
{
    bool isOk = false;
    auto result = decode(inputString, isOk);
    if (!isOk)
        throw exception here;
    return result;
}
```

2024-09-09 08:04 UTC, lokihi commented on test/base64_test.cpp
> +    ASSERT_EQ(expected, flag);
Исправил

2024-09-09 08:04 UTC, lokihi commented on test/base64_test.cpp
> +    const std::string decoded{base64::decode({"123"},flag)};
Исправил

2024-09-09 08:04 UTC, lokihi commented on test/base64_file_test.cpp
> +#include <gtest/gtest.h>
Исправил

2024-09-09 08:04 UTC, lokihi commented on README.md
> +If an exception is caught, the value of the иoolean variable will be changed to false
Исправил

2024-09-09 08:25 UTC, lokihi commented on include/base64.hpp
> +        const uint8_t symbol1 = *inputIterator++;
Как я понял, в цикле такое такое инкрементирование эффективнее, а здесь нам нужно сначала значение получать, а потом обращаться к следующему элементу строки

2024-09-09 08:53 UTC, lokihi commented on include/base64.hpp
> +inline void decodingMainPartString(std::string_view inputString, int numPadding, std::string &outputString)
Исправил

2024-09-09 08:54 UTC, lokihi commented on include/base64.hpp
> +        std::uint32_t const concatenatedBits = (decodeTable[currentBlock[0]] << 18) | (decodeTable[currentBlock[1]] << 12) |
Исправил

2024-09-09 08:54 UTC, lokihi commented on include/base64.hpp
> +inline void decodingPaddingChar(std::string_view inputString, int numPadding, std::string &outputString)
Исправил

2024-09-09 08:54 UTC, lokihi commented on include/base64.hpp
> +    case 0:
Сделал

2024-09-09 08:54 UTC, lokihi commented on include/base64.hpp
> +
Исправил

2024-09-09 08:54 UTC, lokihi commented on include/base64.hpp
> +        isOk = false;
Исправил

2024-09-09 08:54 UTC, lokihi commented on include/base64.hpp
> +    if ((inputDataSize-ammountNewline)%4!=0)
Исправил

2024-09-09 08:54 UTC, lokihi commented on include/base64.hpp
> +inline std::string decode(std::string_view inputString)
Сделал

2024-09-09 10:51 UTC, aasirotkin approved these changes

2024-09-09 10:51 UTC, aasirotkin commented on include/base64.hpp
> +        isOk = false;
Ну а тут почему не вернул сразу строку?

2024-09-09 14:50 UTC, lokihi commented on include/base64.hpp
> +        isOk = false;
Сделал

2024-09-10 06:48 UTC, aasirotkin approved these changes
Дима, это точно последнее! До обеда сделаем и попрощаемся)))

2024-09-10 06:48 UTC, aasirotkin commented on include/base64.hpp
> +        if (currentBlock[counterBlock] != '\n' && currentBlock[counterBlock]!='\r')
Пробельчики вокруг !=

2024-09-10 06:48 UTC, aasirotkin commented on include/base64.hpp
> +    isOk = true;
Дим, смотри. Из-за этого true у тебя получается 6 дополнительных строк, 4 - на скобочки и 2 на isOk = false.
А если ты тут сделаешь isOk = false, то скобочки уходят и ты просто возвращаешь string{};, кстати скобочки можно убрать и у проверки на пустую строку, кодстайл это позволяет.

Итого, меняем true на false, и в самом конце не забываем выставить true, вместо 6 дополнительных строк, получаем 1 дополнительную. Плюс такого подхода ещё и в том, что не нужно выставлять false посередине, не нужно про это помнить.

Вот такой подход, очень поход на RAII, если не знаешь, то почитай

2024-09-10 06:48 UTC, aasirotkin commented on include/base64.hpp
> +} // namespace base64
Опять этот Тупик тут) Рекомендую добавить перенос строки

2024-09-10 06:48 UTC, aasirotkin commented on test/base64_test.cpp
> +    const std::string decoded{base64::decode({"123456=="},flag)};
Где-то есть пробел после запятой, а где-то нет.
Добавь везде пожалуйста.

Однотипность оформления однажды очень тебе поможет. К примеру когда будешь писать regexp какой-нибудь

2024-09-10 07:38 UTC, lokihi commented on include/base64.hpp
> +        if (currentBlock[counterBlock] != '\n' && currentBlock[counterBlock]!='\r')
Сделал

2024-09-10 07:39 UTC, lokihi commented on include/base64.hpp
> +    isOk = true;
Сделал

2024-09-10 07:39 UTC, lokihi commented on include/base64.hpp
> +} // namespace base64
Сделал

2024-09-10 07:47 UTC, lokihi commented on test/base64_test.cpp
> +    const std::string decoded{base64::decode({"123456=="},flag)};
Исправил

2024-09-10 08:11 UTC, merged